language: python
cache: pip
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
- python setup.py -q install
script:
- pytest
notifications:
  email: false
deploy:
  provider: pypi
  user: skar404
  password:
    secure: ZsedXSX5jNHE0CknZnOyu8waV6vJF0ARq1490v7w7/bE7Ldcza+CqSmZe9ltCxtE1Wiy2mvU3IMfs/GLLOCDCvdNA5UszPvca/cKA9s7pYvO/grW3e9Wp+ol9xd1JNja3Aov7HahY1W6x4lHWxjSbJ8fduRbmmtP9mESOMu2k+yGV5d8+TGkzqNOw28abPoKCRHFEbRP2Ft4l2BrSC5UizxRBgbEu82Swfu8aeL/QCLTrTCVB2U1zMaKn0UR7vYUiOTLDn49SaZ5MJq9Fmoe90pmQmR2rMGycn5r8iN494rzrb6wk1RYRAmauV1mT3Hi2nq3FsMbB7YArUNQzO8mFoUAtp3+U4bcFUAU+ZF4xhMwwDjXpBmgEb/m3B9YcRmbGHLyfQKYHwGrn7AdcsHiUCti8lEHbxmCsdtKlmvNIgoKFUrn8A04QfDKA5wqKKfQeXxyzzNsFjY9DUE8shtI4/GQT+v3SeGUNIoyJ9Kt5gYxQHAYMTKtCbBYWi8aKgsnW5/dfnMH9HLSPwYtpXF4P99IWZMNDg3/GZ6z3bS2o8nu0b5jWfSdt7sthmo2WJobEQ2Z+5xra72GYdcHwppbVfGPfulKjA3Y46ydLj1J5hCAsq8NB4lPOqsueG3uExQOsGa3GKAvd5duZV8LXdTuKgUmJMkg8ZD3KNNQx7CKQUc=
