language: python
cache: pip
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
- python setup.py -q install
script:
- pytest
notifications:
  email: true
deploy:
  provider: pypi
  user: romgar
  password:
    secure: TO/PuxMq+Uqjg70SKVhlbGxhnkYE7sc004iBXnuylP/yJLyZTKtRC0z1SPVknxoSsa+IVCfg1mnNW9bJDZfROp7TlU36/af16sOMOnUKFYISDKBub4o08xykhgVG6Wg1Bgkez7pTHXxHYLyEmdhMOp2S/IqYF1+TBu3Il5n+nGWCq+1AoT9cOFdcM9FF6TQ2KNZrm6KBIv/3nS/0YwUxUYkghy9oLVf+tkaX76sNmff0wNnKCWmf9zbiiEtY7WnKHdnvldIZlkVyLwugxhukgbEbSpgWh+athWxpBUoPBzKsUt/izQQRceU+iP3RDJmN/4u/gMPEN4woPfqoZAvRpL6ujeoUxXncebPx5j9gdnUxgwLgc88QN6Ipt8yaYV90dtuEKXyMMTuhtZOFh36qaOPuWZHJjnKuDcuL606HaN7cw/aWFnxgOI3Oow5avuPyztOLGUJXqL+jgy7WZUuxb9VRxRaFcR9ECsySDlLhCflQx0FrBdxlNPQhWBkFyeNh4lyOMgSdwdizc07V64bkAB05lAvBZuRTkbjRq3j/+/rPFYxF0O46eqF7bUcqLupJE8YhIAKF8JHXWNW26amkzll4nLOiU1dXEc54uvlIaRgHfLY5k6x2BBT/lJmB+Ar8QPwzaYUvxMYqfcrPenkjKWkZ0nTgTaY0k9BngCjMUX0=
  on:
    branch: master
